name:                rere-hs
version:             0.1.0.0
github:              "ej-shafran/rere-hs"
license:             BSD-3-Clause
author:              "ej-shafran"
maintainer:          "ejshafran@hilma.tech"
copyright:           "2024 ej-shafran"

extra-source-files:
- README.org

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/ej-shafran/rere-hs#readme>

dependencies:
- base >= 4.7 && < 5
- parsec
- process
- directory

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  rere-hs-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - rere-hs
